// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: currency.proto

package currencypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CurrencyClient is the client API for Currency service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CurrencyClient interface {
	Do(ctx context.Context, in *CurRequest, opts ...grpc.CallOption) (*CurResponse, error)
	DoStrm(ctx context.Context, in *CurRequest, opts ...grpc.CallOption) (Currency_DoStrmClient, error)
}

type currencyClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrencyClient(cc grpc.ClientConnInterface) CurrencyClient {
	return &currencyClient{cc}
}

func (c *currencyClient) Do(ctx context.Context, in *CurRequest, opts ...grpc.CallOption) (*CurResponse, error) {
	out := new(CurResponse)
	err := c.cc.Invoke(ctx, "/api.Currency/Do", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyClient) DoStrm(ctx context.Context, in *CurRequest, opts ...grpc.CallOption) (Currency_DoStrmClient, error) {
	stream, err := c.cc.NewStream(ctx, &Currency_ServiceDesc.Streams[0], "/api.Currency/DoStrm", opts...)
	if err != nil {
		return nil, err
	}
	x := &currencyDoStrmClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Currency_DoStrmClient interface {
	Recv() (*CurResponse, error)
	grpc.ClientStream
}

type currencyDoStrmClient struct {
	grpc.ClientStream
}

func (x *currencyDoStrmClient) Recv() (*CurResponse, error) {
	m := new(CurResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CurrencyServer is the server API for Currency service.
// All implementations should embed UnimplementedCurrencyServer
// for forward compatibility
type CurrencyServer interface {
	Do(context.Context, *CurRequest) (*CurResponse, error)
	DoStrm(*CurRequest, Currency_DoStrmServer) error
}

// UnimplementedCurrencyServer should be embedded to have forward compatible implementations.
type UnimplementedCurrencyServer struct {
}

func (UnimplementedCurrencyServer) Do(context.Context, *CurRequest) (*CurResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}
func (UnimplementedCurrencyServer) DoStrm(*CurRequest, Currency_DoStrmServer) error {
	return status.Errorf(codes.Unimplemented, "method DoStrm not implemented")
}

// UnsafeCurrencyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurrencyServer will
// result in compilation errors.
type UnsafeCurrencyServer interface {
	mustEmbedUnimplementedCurrencyServer()
}

func RegisterCurrencyServer(s grpc.ServiceRegistrar, srv CurrencyServer) {
	s.RegisterService(&Currency_ServiceDesc, srv)
}

func _Currency_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Currency/Do",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServer).Do(ctx, req.(*CurRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Currency_DoStrm_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CurRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CurrencyServer).DoStrm(m, &currencyDoStrmServer{stream})
}

type Currency_DoStrmServer interface {
	Send(*CurResponse) error
	grpc.ServerStream
}

type currencyDoStrmServer struct {
	grpc.ServerStream
}

func (x *currencyDoStrmServer) Send(m *CurResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Currency_ServiceDesc is the grpc.ServiceDesc for Currency service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Currency_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Currency",
	HandlerType: (*CurrencyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _Currency_Do_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DoStrm",
			Handler:       _Currency_DoStrm_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "currency.proto",
}
