// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: currency.proto

package currencypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Перечисление доступных стран
type Countries int32

const (
	Countries_USA     Countries = 0
	Countries_Ukraine Countries = 1
	Countries_Spain   Countries = 2
	Countries_Belarus Countries = 3
	Countries_Japan   Countries = 4
)

// Enum value maps for Countries.
var (
	Countries_name = map[int32]string{
		0: "USA",
		1: "Ukraine",
		2: "Spain",
		3: "Belarus",
		4: "Japan",
	}
	Countries_value = map[string]int32{
		"USA":     0,
		"Ukraine": 1,
		"Spain":   2,
		"Belarus": 3,
		"Japan":   4,
	}
)

func (x Countries) Enum() *Countries {
	p := new(Countries)
	*p = x
	return p
}

func (x Countries) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Countries) Descriptor() protoreflect.EnumDescriptor {
	return file_currency_proto_enumTypes[0].Descriptor()
}

func (Countries) Type() protoreflect.EnumType {
	return &file_currency_proto_enumTypes[0]
}

func (x Countries) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Countries.Descriptor instead.
func (Countries) EnumDescriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{0}
}

// Перечисление доступных валют
type Currencies int32

const (
	Currencies_Dollar   Currencies = 0
	Currencies_Hryvnia  Currencies = 1
	Currencies_Euro     Currencies = 2
	Currencies_BelRuble Currencies = 3
	Currencies_Yen      Currencies = 4
)

// Enum value maps for Currencies.
var (
	Currencies_name = map[int32]string{
		0: "Dollar",
		1: "Hryvnia",
		2: "Euro",
		3: "BelRuble",
		4: "Yen",
	}
	Currencies_value = map[string]int32{
		"Dollar":   0,
		"Hryvnia":  1,
		"Euro":     2,
		"BelRuble": 3,
		"Yen":      4,
	}
)

func (x Currencies) Enum() *Currencies {
	p := new(Currencies)
	*p = x
	return p
}

func (x Currencies) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currencies) Descriptor() protoreflect.EnumDescriptor {
	return file_currency_proto_enumTypes[1].Descriptor()
}

func (Currencies) Type() protoreflect.EnumType {
	return &file_currency_proto_enumTypes[1]
}

func (x Currencies) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currencies.Descriptor instead.
func (Currencies) EnumDescriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{1}
}

// Запрос, включающий название страны
type CurRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message Countries `protobuf:"varint,1,opt,name=message,proto3,enum=api.Countries" json:"message,omitempty"`
}

func (x *CurRequest) Reset() {
	*x = CurRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_currency_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurRequest) ProtoMessage() {}

func (x *CurRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurRequest.ProtoReflect.Descriptor instead.
func (*CurRequest) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{0}
}

func (x *CurRequest) GetMessage() Countries {
	if x != nil {
		return x.Message
	}
	return Countries_USA
}

// Ответ, содержащий валюту и её значение в рублях
type CurResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Currency Currencies `protobuf:"varint,1,opt,name=currency,proto3,enum=api.Currencies" json:"currency,omitempty"`
	Value    int32      `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CurResponse) Reset() {
	*x = CurResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_currency_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurResponse) ProtoMessage() {}

func (x *CurResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurResponse.ProtoReflect.Descriptor instead.
func (*CurResponse) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{1}
}

func (x *CurResponse) GetCurrency() Currencies {
	if x != nil {
		return x.Currency
	}
	return Currencies_Dollar
}

func (x *CurResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_currency_proto protoreflect.FileDescriptor

var file_currency_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x36, 0x0a, 0x0a, 0x43, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x50, 0x0a,
	0x0b, 0x43, 0x75, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52,
	0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a,
	0x44, 0x0a, 0x09, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x07, 0x0a, 0x03,
	0x55, 0x53, 0x41, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6b, 0x72, 0x61, 0x69, 0x6e, 0x65,
	0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x70, 0x61, 0x69, 0x6e, 0x10, 0x02, 0x12, 0x0b, 0x0a,
	0x07, 0x42, 0x65, 0x6c, 0x61, 0x72, 0x75, 0x73, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x4a, 0x61,
	0x70, 0x61, 0x6e, 0x10, 0x04, 0x2a, 0x46, 0x0a, 0x0a, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x69, 0x65, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x6f, 0x6c, 0x6c, 0x61, 0x72, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x48, 0x72, 0x79, 0x76, 0x6e, 0x69, 0x61, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04,
	0x45, 0x75, 0x72, 0x6f, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x65, 0x6c, 0x52, 0x75, 0x62,
	0x6c, 0x65, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x59, 0x65, 0x6e, 0x10, 0x04, 0x32, 0x62, 0x0a,
	0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x27, 0x0a, 0x02, 0x44, 0x6f, 0x12,
	0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x75, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x44, 0x6f, 0x53, 0x74, 0x72, 0x6d, 0x12, 0x0f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x43, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x43, 0x75, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30,
	0x01, 0x42, 0x19, 0x5a, 0x17, 0x2e, 0x2f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65,
	0x73, 0x2f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_currency_proto_rawDescOnce sync.Once
	file_currency_proto_rawDescData = file_currency_proto_rawDesc
)

func file_currency_proto_rawDescGZIP() []byte {
	file_currency_proto_rawDescOnce.Do(func() {
		file_currency_proto_rawDescData = protoimpl.X.CompressGZIP(file_currency_proto_rawDescData)
	})
	return file_currency_proto_rawDescData
}

var file_currency_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_currency_proto_goTypes = []interface{}{
	(Countries)(0),      // 0: api.Countries
	(Currencies)(0),     // 1: api.Currencies
	(*CurRequest)(nil),  // 2: api.CurRequest
	(*CurResponse)(nil), // 3: api.CurResponse
}
var file_currency_proto_depIdxs = []int32{
	0, // 0: api.CurRequest.message:type_name -> api.Countries
	1, // 1: api.CurResponse.currency:type_name -> api.Currencies
	2, // 2: api.Currency.Do:input_type -> api.CurRequest
	2, // 3: api.Currency.DoStrm:input_type -> api.CurRequest
	3, // 4: api.Currency.Do:output_type -> api.CurResponse
	3, // 5: api.Currency.DoStrm:output_type -> api.CurResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_currency_proto_init() }
func file_currency_proto_init() {
	if File_currency_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_currency_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_currency_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_currency_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_currency_proto_goTypes,
		DependencyIndexes: file_currency_proto_depIdxs,
		EnumInfos:         file_currency_proto_enumTypes,
		MessageInfos:      file_currency_proto_msgTypes,
	}.Build()
	File_currency_proto = out.File
	file_currency_proto_rawDesc = nil
	file_currency_proto_goTypes = nil
	file_currency_proto_depIdxs = nil
}
